_base_ = ["./sparsedrive_small_stage1.py"]

roi_size = (30, 60)
polygon_occ_num_sample = 32
polygon_occ_num_anchor = 100

task_config = dict(
    with_det=True,
    with_map=False,
    with_occ=True,
    with_motion_plan=False,
)

polygon_occ_train_pipeline = [
    dict(type="LoadMultiViewImageFromFiles", to_float32=True),
    dict(
        type="LoadPointsFromFile",
        coord_type="LIDAR",
        load_dim=5,
        use_dim=5,
        file_client_args=dict(backend="disk"),
    ),
    dict(type="ResizeCropFlipImage"),
    dict(
        type="MultiScaleDepthMapGenerator",
        downsample=[4, 8, 16],
    ),
    dict(type="BBoxRotation"),
    dict(type="PhotoMetricDistortionMultiViewImage"),
    dict(
        type="NormalizeMultiviewImage",
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True,
    ),
    dict(
        type="CircleObjectRangeFilter",
        class_dist_thred=[55] * 10,
    ),
    dict(
        type="InstanceNameFilter",
        classes=[
            "car",
            "truck",
            "construction_vehicle",
            "bus",
            "trailer",
            "barrier",
            "motorcycle",
            "bicycle",
            "pedestrian",
            "traffic_cone",
        ],
    ),
    dict(
        type="VectorizePolygonOcc",
        roi_size=roi_size,
        normalize=False,
        sample_num=polygon_occ_num_sample,
        closed_only=True,
    ),
    dict(type="NuScenesSparse4DAdaptor"),
    dict(
        type="Collect",
        keys=[
            "img",
            "timestamp",
            "projection_mat",
            "image_wh",
            "gt_depth",
            "focal",
            "gt_bboxes_3d",
            "gt_labels_3d",
            "gt_polygon_occ_labels",
            "gt_polygon_occ_pts",
            "gt_agent_fut_trajs",
            "gt_agent_fut_masks",
            "gt_ego_fut_trajs",
            "gt_ego_fut_masks",
            "gt_ego_fut_cmd",
            "ego_status",
        ],
        meta_keys=["T_global", "T_global_inv", "timestamp", "instance_id"],
    ),
]

model = dict(
    head=dict(
        task_config=task_config,
        map_head=None,
        polygon_occ_head=dict(
            type="PolygonOccHead",
            cls_threshold_to_reg=0.05,
            decouple_attn=False,
            instance_bank=dict(
                type="InstanceBank",
                num_anchor=polygon_occ_num_anchor,
                embed_dims=256,
                anchor="data/kmeans/kmeans_polygon_occ_100.npy",
                anchor_handler=dict(type="SparsePoint3DKeyPointsGenerator"),
                num_temp_instances=0,
                confidence_decay=0.6,
                feat_grad=True,
            ),
            anchor_encoder=dict(
                type="SparsePoint3DEncoder",
                embed_dims=256,
                num_sample=polygon_occ_num_sample,
            ),
            num_single_frame_decoder=1,
            operation_order=[
                "gnn",
                "norm",
                "deformable",
                "ffn",
                "norm",
                "refine",
                "temp_gnn",
                "gnn",
                "norm",
                "deformable",
                "ffn",
                "norm",
                "refine",
                "temp_gnn",
                "gnn",
                "norm",
                "deformable",
                "ffn",
                "norm",
                "refine",
                "temp_gnn",
                "gnn",
                "norm",
                "deformable",
                "ffn",
                "norm",
                "refine",
                "temp_gnn",
                "gnn",
                "norm",
                "deformable",
                "ffn",
                "norm",
                "refine",
                "temp_gnn",
                "gnn",
                "norm",
                "deformable",
                "ffn",
                "norm",
                "refine",
            ],
            temp_graph_model=dict(
                type="MultiheadFlashAttention",
                embed_dims=256,
                num_heads=8,
                batch_first=True,
                dropout=0.1,
            ),
            graph_model=dict(
                type="MultiheadFlashAttention",
                embed_dims=256,
                num_heads=8,
                batch_first=True,
                dropout=0.1,
            ),
            norm_layer=dict(type="LN", normalized_shape=256),
            ffn=dict(
                type="AsymmetricFFN",
                in_channels=512,
                pre_norm=dict(type="LN"),
                embed_dims=256,
                feedforward_channels=1024,
                num_fcs=2,
                ffn_drop=0.1,
                act_cfg=dict(type="ReLU", inplace=True),
            ),
            deformable_model=dict(
                type="DeformableFeatureAggregation",
                embed_dims=256,
                num_groups=8,
                num_levels=4,
                num_cams=6,
                attn_drop=0.15,
                use_deformable_func=True,
                use_camera_embed=True,
                residual_mode="cat",
                kps_generator=dict(
                    type="SparsePoint3DKeyPointsGenerator",
                    embed_dims=256,
                    num_sample=polygon_occ_num_sample,
                    num_learnable_pts=3,
                    fix_height=(0, 0.5, -0.5, 1, -1),
                    ground_height=-1.84023,
                ),
            ),
            refine_layer=dict(
                type="SparsePoint3DRefinementModule",
                embed_dims=256,
                num_sample=polygon_occ_num_sample,
                num_cls=3,
            ),
            sampler=dict(
                type="SparsePolygonTarget",
                assigner=dict(
                    type="HungarianLinesAssigner",
                    cost=dict(
                        type="MapQueriesCost",
                        cls_cost=dict(type="FocalLossCost", weight=1.0),
                        reg_cost=dict(
                            type="LinesL1Cost",
                            weight=10.0,
                            beta=0.01,
                            permute=False,
                        ),
                    ),
                ),
                num_cls=3,
                num_sample=polygon_occ_num_sample,
                roi_size=roi_size,
            ),
            loss_cls=dict(
                type="FocalLoss",
                use_sigmoid=True,
                gamma=2.0,
                alpha=0.25,
                loss_weight=1.0,
            ),
            loss_reg=dict(
                type="SparseLineLoss",
                loss_line=dict(
                    type="LinesL1Loss",
                    loss_weight=10.0,
                    beta=0.01,
                ),
                num_sample=polygon_occ_num_sample,
                roi_size=roi_size,
            ),
            decoder=dict(type="SparsePolygonOccDecoder"),
            reg_weights=[1.0] * (polygon_occ_num_sample * 2),
            gt_cls_key="gt_polygon_occ_labels",
            gt_reg_key="gt_polygon_occ_pts",
            gt_id_key="map_instance_id",
            with_instance_id=False,
            task_prefix="polygon_occ",
        ),
    )
)

data = dict(
    train=dict(
        pipeline=polygon_occ_train_pipeline,
    ),
)

eval_mode = dict(
    with_det=True,
    with_tracking=True,
    with_map=False,
    with_motion=False,
    with_planning=False,
    tracking_threshold=0.2,
    motion_threshhold=0.2,
)

evaluation = dict(
    eval_mode=eval_mode,
)
